set -e
dataset=$1
gpu_ids=$2


cd DialogueGCN
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=2 --windowf=2 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66






CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66



CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=1 --windowf=1 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66






CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=3 --windowf=3 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66







CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.0' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.0' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.0' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.1' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.1' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.1' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.2' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.2' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.2' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.3' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.3' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.3' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.4' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.4' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.4' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.5' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.5' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.5' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.6' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.6' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.6' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66


CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=50 --mask-type='constant-0.7' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=100 --mask-type='constant-0.7' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66
CUDA_VISIBLE_DEVICES=$gpu_ids python -u train_gcnet.py --epoch=100 --lr=0.001 --hidden=200 --mask-type='constant-0.7' --windowp=4 --windowf=4 --base-model='LSTM' --loss-recon --dataset=$dataset --audio-feature='wav2vec-large-c-UTT' --text-feature='deberta-large-4-UTT' --video-feature='manet_UTT' --time-attn --seed=66

